name: Terraform Plan

on:
  pull_request:
    branches:
      - master
  push:
    paths:
      - 'apps/jenkins/**'
    

permissions:
  pull-requests: write


jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./apps/jenkins/terraform

    - name: Validate Terraform
      run: terraform validate
      working-directory: ./apps/jenkins/terraform

    - name: Terraform Plan only
      run: terraform plan
      working-directory: ./apps/jenkins/terraform
     
    - name: Plan Terraform
      id: plan
      run: terraform plan -no-color -input=false 
      working-directory: ./apps/jenkins/terraform
          

    - name: truncate terraform plan result
      run: |
        echo "$(terraform output --json)" | jq -r 'keys[] as $k | "\($k)=\(.[$k].value)"' >> $GITHUB_OUTPUT
        echo "$(terraform output --json)" | jq -r 'keys[] as $k | "\($k)=\(.[$k].value)"' >> $GITHUB_ENV
      working-directory: ./apps/jenkins/terraform
  
    
    - name: post plan as sticky comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: plan
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>

          ```
          ${{ env.PLAN }}
          ```

          </details>
          
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.TF_WORK_DIR }}\`, Workflow: \`${{ github.workflow }}\`*`

  