name: Terraform Format

on:
  push:
    paths:
      - 'apps/**'

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform fmt
      id: fmt
      run: |
        terraform fmt -recursive
        terraform fmt -check
      continue-on-error: true
      working-directory: ./apps/

    - name: Commit
      run: |
        git config --global user.name 'Asim Daud'
        git config --global user.email 'asimdadu@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git commit -am "Automated report"
        git push
