name: Terraform Plan

on:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $AWS_REGION

    - name: Change directory
      run: cd/terraform/test

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform.test

    - name: Validate Terraform
      run: terraform validate
      working-directory: ./terraform.test

    - name: Plan Terraform
      id: plan
      run: terraform plan -no-color > plan.txt
      working-directory: ./terraform.test

    - name: Post Plan to PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: plan.txt
